export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const SEARCH_PRODUCT_PARAM = "SEARCH_PRODUCT_PARAM";
export const COUNT_PRODUCT = "COUNT_PRODUCT";
export const FILTER_PRICE_PRODUCT = "FILTER_PRICE_PRODUCT";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FIND_CATEGORY_BY_ID = "FIND_CATEGORY_BY_ID";

export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
